services:
  api:
    image: ghcr.io/loan-mgt/cpe-calendar:latest
    container_name: cycling-api
    restart: unless-stopped
    ports:
      - "9210:8080"
    environment:
      - TIMEZONE=${TIMEZONE}
    # volumes:
    #   - /var/log:/root/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      default:
        aliases:
          - api

networks: {}
